version: '3.8'

volumes:
  node-ipc:
  node-db:

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION:-10.5.1}
    environment:
      NETWORK: ${NETWORK:-preprod}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"
  hydra-node:
    image: ghcr.io/cardano-scaling/hydra-node:0.22.0
    command: [] #  appropriate command accordint to your cluster configuration
    volumes:
      - node-ipc:/ipc

  kuber-hydra:
    image: dquadrant/kuber-hydra:latest
    ports:
      - "8081:8081"
    environment:
      HYDRA_URL: "hydra-node:5001"
      CARDANO_NODE_SOCKET_PATH: "/ipc/node.socket"
      NETWORK: ${NETWORK:-preprod}
    volumes:
      - node-ipc:/ipc
    depends_on:
      - cardano-node
      - hydra-node
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"
