#!/usr/bin/env bash
set -eo pipefail;

EXECUTABLE="./.docker/build"

WORKDIR=$(pwd)
DIST_NEWSTYLE_DIR="${WORKDIR}/dist-newstyle/build/docker/dist-newstyle/"
CABAL_CACHE_DIR="${WORKDIR}/dist-newstyle/build/docker/cabal-cache/"
CHROOT_DIR="${WORKDIR}/dist-newstyle/build/docker/chroot-env/"

mkdir -p $DIST_NEWSTYLE_DIR; mkdir -p $CABAL_CACHE_DIR ; mkdir -p $CHROOT_DIR

# Variables for multiarch support
PLATFORMS="linux/amd64,linux/arm64"
USE_BUILDX=false
PUSH_IMAGE=false

function echo-usage() {
  echo "  Usage $EXECUTABLE [options]"
  echo "    Options:"
  echo "      -h, --help               -->  Show this help message"
  echo "      --multiarch              -->  Build for multiple architectures (amd64, arm64)"
  echo "      --push                   -->  Push image to registry (requires --multiarch)"
  echo "      --platforms PLATFORMS    -->  Specify platforms (default: linux/amd64,linux/arm64)"
  echo ""
  echo "    Examples:"
  echo "      Set up                   -->  $EXECUTABLE cabal update"
  echo "      Build an image           -->  $EXECUTABLE"
  echo "      Build with specific tag  -->  $EXECUTABLE -t dquadrant/kuber:local"
  echo "      Build multiarch (local)  -->  $EXECUTABLE --multiarch -t dquadrant/kuber:local"
  echo "      Build multiarch (push)   -->  $EXECUTABLE --multiarch --push -t dquadrant/kuber:latest"
  echo "      Clean up caches          -->  $EXECUTABLE clean"
}


if [ ! -f ./cabal.project ]
then
  echo "    Missing cabal.project file current directory";
  echo;echo-usage
  exit 1
fi

## Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      echo-usage
      exit 0
      ;;
    --multiarch)
      USE_BUILDX=true
      shift
      ;;
    --push)
      PUSH_IMAGE=true
      shift
      ;;
    --platforms)
      PLATFORMS="$2"
      shift 2
      ;;
    clean)
      for dir in "$HOME/.cabal-docker" "./dist-newstyle-docker"  "./chroot-env"
      do
        echo "  Removing  $dir";
        rm -rf $dir;
      done;
      exit;
      ;;
    *)
      break
      ;;
  esac
done

## print help
if  grep -qE '^--h'  <<< "$*"  ||   grep -qE "^-h" -  <<< "$*"
then
  echo-usage
  exit 1;
fi

## clean command for freeing up the caches used for build
if ( grep -qE 'clean' <<< "$*")
then
  for dir in "$HOME/.cabal-docker" "./dist-newstyle-docker"  "./chroot-env"
  do
    echo "  Removing  $dir";
    rm -rf $dir;
  done;
  exit;
fi

function showCommand() {
  echo "+ $*"
  "$@"
}


## execute a command inside the build image
function execute-isolated() {
  echo "+ execute-isolated $*"
  docker run -i -u"$(id -u):$(id -g)" \
  -v $CABAL_CACHE_DIR:$HOME/.cabal \
  -v $CABAL_CACHE_DIR:/.cabal \
	-v $DIST_NEWSTYLE_DIR:$WORKDIR/dist-newstyle/ \
  -v $CHROOT_DIR:/chroot-env/ \
  -v $WORKDIR:$WORKDIR \
  -e OVERRIDE_CHROOT_DIR=/chroot-env \
	-e HOME=$HOME \
	--entrypoint /bin/bash \
	--workdir $WORKDIR \
	cardanoapi/haskell:9.6.1 -c  "$*"
}

if [[ "$1" == cabal* ]] ; then
    execute-isolated "$@" # execute the cabal command
else
    ## default build
    execute-isolated 'cabal build exe:kuber-server exe:kuber-hydra  && bash -e ./.ci/copy-libraries.sh'

    ## build final docker image using docker buildx for multiarch support
    if [ "$USE_BUILDX" = true ]; then
      echo "Building multiarch image with docker buildx for platforms: $PLATFORMS"
      
      # Determine build flags
      BUILD_FLAGS="--build-arg OVERRIDE_CHROOT_DIR=./dist-newstyle/build/docker/chroot-env/ -f ./.ci/Dockerfile"
      
      if [ "$PUSH_IMAGE" = true ]; then
        BUILD_FLAGS="$BUILD_FLAGS --push"
      else
        BUILD_FLAGS="$BUILD_FLAGS --load"
      fi
      
      BUILD_FLAGS="$BUILD_FLAGS --platform $PLATFORMS"
      
      # Add user-provided arguments (like -t tag)
      if [ $# -gt 0 ]; then
        showCommand docker buildx build $BUILD_FLAGS "$@" .
      elif git describe --tags | grep -qE '^[0-9]+(\.[0-9]+)*$'; then
        showCommand docker buildx build $BUILD_FLAGS -t "dquadrant/kuber:$(git describe --tags)" .
      else
        showCommand docker buildx build $BUILD_FLAGS -t "dquadrant/kuber:$(git rev-parse HEAD)" .
      fi
    else
      ## Standard single-arch build with docker build
      if [ $# -gt 0 ]; then
        showCommand docker build --build-arg OVERRIDE_CHROOT_DIR=./dist-newstyle/build/docker/chroot-env/ -f ./.ci/Dockerfile "$@" .
      elif git describe --tags | grep -qE '^[0-9]+(\.[0-9]+)*$'; then
        showCommand docker build --build-arg OVERRIDE_CHROOT_DIR=./dist-newstyle/build/docker/chroot-env/ -f ./.ci/Dockerfile -t "dquadrant/kuber:$(git describe --tags)" .
      else
        showCommand docker build --build-arg OVERRIDE_CHROOT_DIR=./dist-newstyle/build/docker/chroot-env/ -f ./.ci/Dockerfile -t "dquadrant/kuber:$(git rev-parse HEAD)" .
      fi
    fi
fi
