name: Docusaurus Build and Deploy

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./docs

      - name: Build Docusaurus site
        run: npm run build
        working-directory: ./docs

      - name: Deploy Docusaurus to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          destination_dir: hydra_docusaurus
          keep_files: true

      - name: Deploy kuber-haskell-library to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/kuber-haskell-library
          destination_dir: haskell_library
          keep_files: true
